# This is a basic workflow to help you get started with Actions

name: is CI

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      matrix:
        version: 
          - "8.2,latest"
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: run node
        id: env
        run: |
          sudo npm install -g pnpm
          pnpm install
          pnpm start